name: Test setup-elixir
on:
  push:
    paths:
      - "setup-elixir/**"
      - ".github/workflows/test-setup-elixir.yml"
  pull_request:
    paths:
      - "setup-elixir/**"
      - ".github/workflows/test-setup-elixir.yml"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup Elixir
        uses: ./setup-elixir

      - name: Verify installation
        shell: bash
        run: |
          elixir --version
          mix --version
          mix hex.info
