name: Test reusable-cli-proxy-publish (dry-run)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/reusable-cli-proxy-publish.yml"
      - ".github/workflows/test-reusable-cli-proxy-publish.yml"
      - "tests/fixtures/cli-proxy/**"

permissions:
  id-token: write
  contents: read

jobs:
  test-cli-proxy-publish-dry-run:
    uses: ./.github/workflows/reusable-cli-proxy-publish.yml
    with:
      npm-package-dir: tests/fixtures/cli-proxy/npm
      pypi-package-dir: tests/fixtures/cli-proxy/pypi
      publish-npm: true
      publish-pypi: true
      dry-run: ${{ 'true' }}
