name: Test setup-elixir
on:
  push:
    paths:
      - "setup-elixir/**"
      - ".github/workflows/test-setup-elixir.yml"
  pull_request:
    paths:
      - "setup-elixir/**"
      - ".github/workflows/test-setup-elixir.yml"

jobs:
  # TODO: extend matrix to macos when needed
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Elixir
        uses: ./setup-elixir

      - name: Verify installation
        shell: bash
        run: |
          elixir --version
          mix --version
          mix hex.info
